name: 'ZCode IDE Server in Github Actions'
description: 'Start a Zcode IDE Server (on default port 4000)'

branding:
  icon: 'server'
  color: 'purple'

inputs:
  ide-server-version:
    description: 'IDE Server version to use (default "latest")'
    required: false
    default: 'latest'
  ide-server-port:
    description: 'IDE Server port to use (default "4000")'
    required: false
    default: '4000'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mongodb-version }}