name: 'ZCode IDE Server in Github Actions'
description: 'Start a Zcode IDE Server (on default port 4000)'

branding:
  icon: 'server'
  color: 'purple'

inputs:
  ide-server-version:
    description: 'IDE Server version to use (default "latest")'
    required: false
    default: 'latest'
  ide-server-port:
    description: 'IDE Server port to use (default "4000")'
    required: false
    default: '4000'
  ide-server-network:
    description: 'IDE Server network to use (default "host")'
    required: false
    default: 'host'
  ide-server-container-name:
    description: 'IDE Server container name to use (default "test_container")'
    required: false
    default: 'test_container'
  ide-server-key:
    description: 'IDE Server key (default "1234567890")'
    required: false
    default: '1234567890'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ide-server-version }}
    - ${{ inputs.ide-server-port }}
    - ${{ inputs.ide-server-network }}
    - ${{ inputs.ide-server-container-name }}
    - ${{ inputs.ide-server-key }}